package cisprotonigeriamrs;

import com.mysql.jdbc.StringUtils;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import cisprotonigeriamrs.DatabaseHandler;
import cisprotonigeriamrs.FXMLDocumentController;
import static cisprotonigeriamrs.Utility.checkNullValueNumeric;
import static cisprotonigeriamrs.Utility.cleanValueNumeric;
import java.sql.Connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class LoadSettings {

    private static PreparedStatement icconcept;
    private Statement statement;
    private PreparedStatement dropTable;
    private Statement statementalter;
    private Connection statementUpdate;
    private PreparedStatement statementUpdatenow;
    private PreparedStatement dropTables;
    private Statement stmt;
    private PreparedStatement stmt2;
    private PreparedStatement statementUpdatenowp;
    private PreparedStatement statementUpdatenowa;

    public void createMigratefield() {
        try {

            stmt2 = DatabaseHandler.getInstance().getApinConnection().prepareStatement(
                    String.format("DROP PROCEDURE IF EXISTS migrated;"));
            stmt2.execute();
            stmt = DatabaseHandler.getInstance().getApinConnection().createStatement();
            stmt.execute(
                    "CREATE  PROCEDURE `migrated`()"
                    + "BEGIN "
                    + "  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END; "
                    + "  ALTER TABLE `patient` ADD COLUMN migrated TINYINT(1) DEFAULT 0;\n"
                    + "  ALTER TABLE `patient` ADD COLUMN icfmigrated TINYINT(1) DEFAULT 0;\n"
                    + "  ALTER TABLE `pharmacy` ADD COLUMN migrated TINYINT(1) DEFAULT 0;\n"
                    + "  ALTER TABLE `laboratory` ADD COLUMN migrated TINYINT(1) DEFAULT 0;\n"
                    + "  ALTER TABLE `clinicaleval` ADD COLUMN migrated TINYINT(1) DEFAULT 0;\n"
                    + "END");

        } catch (Exception ex) {
            Logger.getLogger(FXMLDocumentController.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    public void createIcformConcept() {
        try {
            DatabaseHandler.getInstance().getApinConnection().setAutoCommit(false);

            dropTable = DatabaseHandler.getInstance().getApinConnection().prepareStatement(
                    String.format("DROP TABLE IF EXISTS %s", "icform_concepts"));
            dropTable.execute();

            String sql_stmt = "CREATE TABLE `icform_concepts` (\n"
                    + "  `concept_id` double DEFAULT NULL,\n"
                    + "  `concept` varchar(255) DEFAULT NULL,\n"
                    + "  `cisproconcepts` varchar(255) DEFAULT NULL,\n"
                    + "  `conceptvalue` varchar(255) DEFAULT NULL\n"
                    + ") ENGINE=InnoDB DEFAULT CHARSET=utf8;";
            statement = DatabaseHandler.getInstance().getApinConnection().createStatement();
            statement.executeUpdate(sql_stmt);

            icconcept = DatabaseHandler.getInstance().getApinConnection().prepareStatement(
                    "INSERT INTO `icform_concepts` (\n"
                    + "  `concept_id`,\n"
                    + "  `concept`,\n"
                    + "  `cisproconcepts`,\n"
                    + "  `conceptvalue`\n"
                    + ") \n"
                    + "VALUES\n"
                    + "  (\n"
                    + "    5588,\n"
                    + "    'MOTHER DECEASED',\n"
                    + "    'pmotheralive',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1593,\n"
                    + "    'MOTHER\\'S NAME',\n"
                    + "    'pmothername',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164936,\n"
                    + "    'Mother\\'s Address',\n"
                    + "    'pmotheradd',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5589,\n"
                    + "    'FATHER DECEASED',\n"
                    + "    'pfatheralive',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1594,\n"
                    + "    'FATHER\\'S NAME',\n"
                    + "    'pfathername',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164939,\n"
                    + "    'Father\\'s Address',\n"
                    + "    'pfatheradd',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164942,\n"
                    + "    'CHILD\\'S PARENT/CAREGIVER ARE',\n"
                    + "    'pcaregiversrelationshipstatus',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5573,\n"
                    + "    'NUMBER OF SIBLINGS',\n"
                    + "    'psiblings',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1727,\n"
                    + "    'SIGNS AND SYMPTOMS',\n"
                    + "    'symptomsreview',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1728,\n"
                    + "    'SIGN/SYMPTOM NAME',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1731,\n"
                    + "    'SIGN/SYMPTOM DURATION',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (1732, 'Duration units', NULL, NULL),\n"
                    + "  (\n"
                    + "    164800,\n"
                    + "    'Tuberculosis screening status',\n"
                    + "    'patacc_tb',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1200,\n"
                    + "    'DEVELOPMENTAL EXAM FINDINGS',\n"
                    + "    'pdevassess',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164134,\n"
                    + "    'Vaccination Complete',\n"
                    + "    'pimmunecomplete',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1151,\n"
                    + "    'Infant feeding method',\n"
                    + "    'pfeedingmode',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    160533,\n"
                    + "    'Previous ARV treatment',\n"
                    + "    'prevarvexp',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162724,\n"
                    + "    'Health facility name',\n"
                    + "    'prevfacilityname',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    159368,\n"
                    + "    'Medication duration',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165301,\n"
                    + "    'Previous ARV exposure other than PMTCT',\n"
                    + "    'ppreviousarvexp',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    159368,\n"
                    + "    'Medication duration',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165675,\n"
                    + "    'Patient has any known drug allergies',\n"
                    + "    'drugallergies',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    160221,\n"
                    + "    'Past medical history added (text)',\n"
                    + "    'pastmedicalhist',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    159910,\n"
                    + "    'past antiretroviral treatment, patient reported',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165305,\n"
                    + "    'Current Medications',\n"
                    + "    'pcurrmeds',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5088,\n"
                    + "    'Temperature (C)',\n"
                    + "    'petemp',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (5087, 'Pulse', 'pepulse', NULL),\n"
                    + "  (\n"
                    + "    5089,\n"
                    + "    'Weight (kg)',\n"
                    + "    'peweight',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5090,\n"
                    + "    'Height (cm)',\n"
                    + "    'pedcircumf',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    980,\n"
                    + "    'BODY SURFACE AREA',\n"
                    + "    'pedsurface',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1343,\n"
                    + "    'MID-UPPER ARM CIRCUMFERENCE',\n"
                    + "    'pedmuac',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165327,\n"
                    + "    'Head/Eye/ENT',\n"
                    + "    'peheadeye',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165327, 'Head/Eye/ENT', NULL, NULL),\n"
                    + "  (165327, 'Head/Eye/ENT', NULL, NULL),\n"
                    + "  (165327, 'Head/Eye/ENT', NULL, NULL),\n"
                    + "  (165327, 'Head/Eye/ENT', NULL, NULL),\n"
                    + "  (165327, 'Head/Eye/ENT', NULL, NULL),\n"
                    + "  (165327, 'Head/Eye/ENT', NULL, NULL),\n"
                    + "  (165327, 'Head/Eye/ENT', NULL, NULL),\n"
                    + "  (165327, 'Head/Eye/ENT', NULL, NULL),\n"
                    + "  (165327, 'Head/Eye/ENT', NULL, NULL),\n"
                    + "  (165327, 'Head/Eye/ENT', NULL, NULL),\n"
                    + "  (165318, 'Skin', 'peskin', NULL),\n"
                    + "  (165318, 'Skin', NULL, NULL),\n"
                    + "  (165318, 'Skin', NULL, NULL),\n"
                    + "  (165318, 'Skin', NULL, NULL),\n"
                    + "  (165318, 'Skin', NULL, NULL),\n"
                    + "  (165318, 'Skin', NULL, NULL),\n"
                    + "  (165318, 'Skin', NULL, NULL),\n"
                    + "  (165318, 'Skin', NULL, NULL),\n"
                    + "  (165318, 'Skin', NULL, NULL),\n"
                    + "  (\n"
                    + "    165339,\n"
                    + "    'Mental State',\n"
                    + "    'gementalstatus',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165339, 'Mental State', NULL, NULL),\n"
                    + "  (165339, 'Mental State', NULL, NULL),\n"
                    + "  (165339, 'Mental State', NULL, NULL),\n"
                    + "  (165339, 'Mental State', NULL, NULL),\n"
                    + "  (165339, 'Mental State', NULL, NULL),\n"
                    + "  (165339, 'Mental State', NULL, NULL),\n"
                    + "  (165339, 'Mental State', NULL, NULL),\n"
                    + "  (165339, 'Mental State', NULL, NULL),\n"
                    + "  (\n"
                    + "    165316,\n"
                    + "    'Respiratory',\n"
                    + "    'gerespiratory',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165316, 'Respiratory', NULL, NULL),\n"
                    + "  (165316, 'Respiratory', NULL, NULL),\n"
                    + "  (165316, 'Respiratory', NULL, NULL),\n"
                    + "  (165316, 'Respiratory', NULL, NULL),\n"
                    + "  (165316, 'Respiratory', NULL, NULL),\n"
                    + "  (165316, 'Respiratory', NULL, NULL),\n"
                    + "  (165316, 'Respiratory', NULL, NULL),\n"
                    + "  (\n"
                    + "    165325,\n"
                    + "    'Neurological',\n"
                    + "    'geneurological',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165325, 'Neurological', NULL, NULL),\n"
                    + "  (165325, 'Neurological', NULL, NULL),\n"
                    + "  (165325, 'Neurological', NULL, NULL),\n"
                    + "  (165325, 'Neurological', NULL, NULL),\n"
                    + "  (165325, 'Neurological', NULL, NULL),\n"
                    + "  (165325, 'Neurological', NULL, NULL),\n"
                    + "  (165325, 'Neurological', NULL, NULL),\n"
                    + "  (165325, 'Neurological', NULL, NULL),\n"
                    + "  (165325, 'Neurological', NULL, NULL),\n"
                    + "  (165325, 'Neurological', NULL, NULL),\n"
                    + "  (\n"
                    + "    165313,\n"
                    + "    'General Appearance',\n"
                    + "    'pegenappearance',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165313,\n"
                    + "    'General Appearance',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165313,\n"
                    + "    'General Appearance',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165313,\n"
                    + "    'General Appearance',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165313,\n"
                    + "    'General Appearance',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165333,\n"
                    + "    'Genitalia',\n"
                    + "    'pegenitalia',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165333, 'Genitalia', NULL, NULL),\n"
                    + "  (165333, 'Genitalia', NULL, NULL),\n"
                    + "  (165333, 'Genitalia', NULL, NULL),\n"
                    + "  (\n"
                    + "    165330,\n"
                    + "    'Gastrointestinal',\n"
                    + "    'gegastrointestinal',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165330,\n"
                    + "    'Gastrointestinal',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165330,\n"
                    + "    'Gastrointestinal',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165330,\n"
                    + "    'Gastrointestinal',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165330,\n"
                    + "    'Gastrointestinal',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165330,\n"
                    + "    'Gastrointestinal',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165326,\n"
                    + "    'Cardiovascular',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165326,\n"
                    + "    'Cardiovascular',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165326,\n"
                    + "    'Cardiovascular',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165326,\n"
                    + "    'Cardiovascular',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165331,\n"
                    + "    'Glands',\n"
                    + "    'pedpeglands',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165331, 'Glands', NULL, NULL),\n"
                    + "  (165331, 'Glands', NULL, NULL),\n"
                    + "  (\n"
                    + "    1391,\n"
                    + "    'PHYSICAL EXAM',\n"
                    + "    'peadditional',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165602,\n"
                    + "    'Assessment',\n"
                    + "    'assessment',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165602, 'Assessment', NULL, NULL),\n"
                    + "  (165602, 'Assessment', NULL, NULL),\n"
                    + "  (165602, 'Assessment', NULL, NULL),\n"
                    + "  (\n"
                    + "    5356,\n"
                    + "    'CURRENT WHO HIV STAGE',\n"
                    + "    'whostage',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165352, 'Plan', 'plan', NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (165352, 'Plan', NULL, NULL),\n"
                    + "  (\n"
                    + "    165355,\n"
                    + "    'Enroll in',\n"
                    + "    'enrollin',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165355, 'Enroll in', NULL, NULL),\n"
                    + "  (165355, 'Enroll in', NULL, NULL),\n"
                    + "  (\n"
                    + "    165361,\n"
                    + "    'ART Plan',\n"
                    + "    'planarvtherapy',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165361, 'ART Plan', NULL, NULL),\n"
                    + "  (165361, 'ART Plan', NULL, NULL),\n"
                    + "  (165361, 'ART Plan', NULL, NULL),\n"
                    + "  (165361, 'ART Plan', NULL, NULL),\n"
                    + "  (\n"
                    + "    161011,\n"
                    + "    'Free text comment',\n"
                    + "    'pedadditional',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5096,\n"
                    + "    'RETURN VISIT DATE',\n"
                    + "    'nextappointment',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1,\n"
                    + "    'Anemia due to Blood Loss',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1060,\n"
                    + "    'Living with partner',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    140238,\n"
                    + "    'Fever',\n"
                    + "    'Fever',\n"
                    + "    'dur_fever'\n"
                    + "  ),\n"
                    + "  (1072, 'Days', NULL, NULL),\n"
                    + "  (\n"
                    + "    163606,\n"
                    + "    'Burning with urination',\n"
                    + "    'Pain on micturation',\n"
                    + "    'dur_painmict'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    832,\n"
                    + "    'Weight loss',\n"
                    + "    'Weight Loss/Failure to gain weight',\n"
                    + "    'dur_weigthl'\n"
                    + "  ),\n"
                    + "  (1073, 'Weeks', NULL, NULL),\n"
                    + "  (\n"
                    + "    864,\n"
                    + "    'GENITAL SORES',\n"
                    + "    'Genital sores/discharge',\n"
                    + "    'dur_gensore'\n"
                    + "  ),\n"
                    + "  (1074, 'Months', NULL, NULL),\n"
                    + "  (\n"
                    + "    133027,\n"
                    + "    'Night sweats',\n"
                    + "    'Night Sweats',\n"
                    + "    'dur_nsweats'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    163074,\n"
                    + "    'Numbness and tingling of skin',\n"
                    + "    'Numbness/Tingling',\n"
                    + "    'dur_numb'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    6023,\n"
                    + "    'Irritability',\n"
                    + "    'Irritability',\n"
                    + "    'dur_irr'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    113054,\n"
                    + "    'Convulsions',\n"
                    + "    'Convulsion',\n"
                    + "    'dur_convul'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    142371,\n"
                    + "    'Difficulty Sleeping',\n"
                    + "    'Difficulty sleeping',\n"
                    + "    'dur_sleep'\n"
                    + "  ),\n"
                    + "  (512, 'Rash', 'Rash', 'dur_rash'),\n"
                    + "  (\n"
                    + "    139084,\n"
                    + "    'Headache',\n"
                    + "    'Headache',\n"
                    + "    'dur_head'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    879,\n"
                    + "    'Itching',\n"
                    + "    'Itching',\n"
                    + "    'dur_itch'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    159298,\n"
                    + "    'visual impairment',\n"
                    + "    'New Visual impairment',\n"
                    + "    'dur_visimp'\n"
                    + "  ),\n"
                    + "  (5622, 'OTHER NON-CODED', NULL, NULL),\n"
                    + "  (\n"
                    + "    873,\n"
                    + "    'OTORRHEA',\n"
                    + "    'Ear Discharge',\n"
                    + "    'dur_eardis'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5244,\n"
                    + "    'ORAL SORES',\n"
                    + "    'Oral Sores',\n"
                    + "    'dur_oralsores'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    142373,\n"
                    + "    'Difficulty breathing',\n"
                    + "    'Shortness of Breath',\n"
                    + "    'dur_shortbreath'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    135595,\n"
                    + "    'Loss of Appetite',\n"
                    + "    'Food refusal',\n"
                    + "    'dur_food'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    142412,\n"
                    + "    'Diarrhea',\n"
                    + "    'Chronic Diarrhea',\n"
                    + "    'dur_diarh'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    133473,\n"
                    + "    'Nausea and Vomiting',\n"
                    + "    'Nausea/Vomitting',\n"
                    + "    'dur_nausea'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    143264,\n"
                    + "    'Cough',\n"
                    + "    'Cough',\n"
                    + "    'dur_cough'\n"
                    + "  ),\n"
                    + "  (1065, 'Yes', 'Yes', NULL),\n"
                    + "  (1116, 'Abnormal', NULL, NULL),\n"
                    + "  (1066, 'No', 'No', NULL),\n"
                    + "  (\n"
                    + "    1173,\n"
                    + "    'EXPRESSED BREASTMILK',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1185,\n"
                    + "    'TREATMENT',\n"
                    + "    'Treatment',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162228,\n"
                    + "    'Allergen detail',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    817,\n"
                    + "    'ABACAVIR / LAMIVUDINE / ZIDOVUDINE',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165304, 'Anti-TB Drugs', NULL, NULL),\n"
                    + "  (\n"
                    + "    165312,\n"
                    + "    'No Significant Findings',\n"
                    + "    'No Significant Findings',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5334,\n"
                    + "    'CANDIDIASIS, ORAL',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    644,\n"
                    + "    'KAPOSI SARCOMA ORAL',\n"
                    + "    'Oral KS',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    139438,\n"
                    + "    'Gingivitis',\n"
                    + "    'Gingivitis',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    131113,\n"
                    + "    'Otitis media',\n"
                    + "    'Otitis media',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    111721,\n"
                    + "    'Mouth ulceration',\n"
                    + "    'Oral ulcer',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (5192, 'Icteric sclera', NULL, NULL),\n"
                    + "  (\n"
                    + "    156441,\n"
                    + "    'fundoscopy abnormal',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1249,\n"
                    + "    'PAPULAR PRURITIC ERUPTION',\n"
                    + "    'Pruritic Paplar Dermatitis',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (140, 'Scabies', 'Scabies', NULL),\n"
                    + "  (\n"
                    + "    117543,\n"
                    + "    'Herpes Zoster',\n"
                    + "    'Herpes Zoster',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (150632, 'Abscess', 'Abcesses', NULL),\n"
                    + "  (\n"
                    + "    165317,\n"
                    + "    'Kaposi\\'s Lesions',\n"
                    + "    'Kaposis Lesions',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    113116,\n"
                    + "    'Seborrheic Dermatitis',\n"
                    + "    'Suborrheic Dermatits',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    171,\n"
                    + "    'Fungal infection',\n"
                    + "    'Fungal Infections',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165335,\n"
                    + "    'Slow mentation',\n"
                    + "    'Slow Mentation',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    121657,\n"
                    + "    'Memory Loss',\n"
                    + "    'Memory Loss',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165336,\n"
                    + "    'Mood swings',\n"
                    + "    'Mood Swings',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    119537,\n"
                    + "    'Depression',\n"
                    + "    'Depression',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (121543, 'Anxiety', 'Anxiety', NULL),\n"
                    + "  (\n"
                    + "    165338,\n"
                    + "    'Suicidal ideation',\n"
                    + "    'Suicidal Ideation',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5242,\n"
                    + "    'Respiratory rate',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    136201,\n"
                    + "    'Labored Breathing',\n"
                    + "    'Labored breathing',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    122863,\n"
                    + "    'Wheezing',\n"
                    + "    'Wheezing',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165314,\n"
                    + "    'Inter/Subcostal recession',\n"
                    + "    'Intercostal (sub)Recession',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    143050,\n"
                    + "    'CYANOSIS',\n"
                    + "    'Cyanosis',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165315,\n"
                    + "    'Auscultation',\n"
                    + "    'Auscultation Findings',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165319,\n"
                    + "    'Disorientated  in TPP',\n"
                    + "    'Disoriented in TPP',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165320,\n"
                    + "    'Impaired Consciousness',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    126351,\n"
                    + "    'Slurred Speech',\n"
                    + "    'Slurred speech',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5170,\n"
                    + "    'NUCHAL RIGIDITY',\n"
                    + "    'Neck Stiffness',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165321,\n"
                    + "    'Blindness 1 or 2 eyes',\n"
                    + "    'Blindness 1/2 Eyes',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165322,\n"
                    + "    'Weakness/Paralysis',\n"
                    + "    'Weakness/paralysis',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165323,\n"
                    + "    'Numbness of extremities',\n"
                    + "    'Numbness/Tingling',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165324,\n"
                    + "    'Fisting/Spacsticity',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (117655, 'Hemiplegia', NULL, NULL),\n"
                    + "  (147096, 'Body Pale', 'Pale', NULL),\n"
                    + "  (\n"
                    + "    142630,\n"
                    + "    'Dehydration',\n"
                    + "    'Dehydrated',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    136443,\n"
                    + "    'Jaundice',\n"
                    + "    'Jaunduce',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165311,\n"
                    + "    'Edematous',\n"
                    + "    'Edematous',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165332,\n"
                    + "    'Genital Lesions',\n"
                    + "    'Genital lesions',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165573,\n"
                    + "    'Genital Discharge',\n"
                    + "    'Genital sores/discharge',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5008,\n"
                    + "    'Hepatomegaly',\n"
                    + "    'Hepatomegaly',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165328,\n"
                    + "    'Tenderness',\n"
                    + "    'Tenderness',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5009,\n"
                    + "    'Splenomegaly',\n"
                    + "    'Spenomegaly',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165329,\n"
                    + "    'Distention',\n"
                    + "    'Dystention',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    136522,\n"
                    + "    'Irregular Heartbeat',\n"
                    + "    'Irregular pulse',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    130792,\n"
                    + "    'Parotid Swelling',\n"
                    + "    'Parotid swelling',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    135488,\n"
                    + "    'Lymphadenopathy',\n"
                    + "    'Discharge',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1068,\n"
                    + "    'Symptomatic',\n"
                    + "    'Symptomatic',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5006,\n"
                    + "    'Asymptomatic',\n"
                    + "    'Asymptomatic',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165307,\n"
                    + "    'AIDS Defining Illness',\n"
                    + "    'AIDS Defining illness',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    131768,\n"
                    + "    'Opportunistic Infectious Disease',\n"
                    + "    'Opportunistic Infections',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1221,\n"
                    + "    'WHO STAGE 2 PEDS',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165341,\n"
                    + "    'Lab Evaluation',\n"
                    + "    'Lab Evaluation',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165342,\n"
                    + "    'OI Therapy',\n"
                    + "    'OI Therapy',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164800,\n"
                    + "    'Tuberculosis screening status',\n"
                    + "    'TB Screening',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165343,\n"
                    + "    'Admission',\n"
                    + "    'Admission',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165344,\n"
                    + "    'OI Prophylaxis',\n"
                    + "    'OI Prophylaxis ',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165345,\n"
                    + "    'Symptomatic treatment',\n"
                    + "    'Symptomatic treatment/Pain control',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165346,\n"
                    + "    'Palliative care',\n"
                    + "    'Palliative care',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5490,\n"
                    + "    'Psychosocial counseling',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165347, 'OVC Care', NULL, NULL),\n"
                    + "  (\n"
                    + "    165348,\n"
                    + "    'End of Life Care',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (12, 'X-ray, chest', 'CXR', NULL),\n"
                    + "  (\n"
                    + "    165350,\n"
                    + "    'Counseling',\n"
                    + "    'Counselling',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5488,\n"
                    + "    'ADHERENCE COUNSELING',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (1356, 'HIV Test', NULL, NULL),\n"
                    + "  (\n"
                    + "    1380,\n"
                    + "    'NUTRITION COUNSELING',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165349,\n"
                    + "    'Peer Health Support',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1272,\n"
                    + "    'REFERRALS ORDERED',\n"
                    + "    'Referrals',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    5486,\n"
                    + "    'SOCIAL SUPPORT SERVICES',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (5576, 'ARV FOR MOTHER', NULL, NULL),\n"
                    + "  (\n"
                    + "    165353,\n"
                    + "    'General Medical Follow-Up',\n"
                    + "    'General Medical Follow up',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165303,\n"
                    + "    'Antiretroviral Therapy',\n"
                    + "    'ARV Therapy',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165354,\n"
                    + "    'Pending Lab Results',\n"
                    + "    'Pending lab results',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165356,\n"
                    + "    'Continue current treatment',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165357,\n"
                    + "    'Start new treatment',\n"
                    + "    'Start new treatment',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162904,\n"
                    + "    'Restart medication',\n"
                    + "    'Restart treatment',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165358,\n"
                    + "    'Change treatment',\n"
                    + "    'Change treatment',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165360,\n"
                    + "    'Stop ART',\n"
                    + "    'Stop treatment',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (968, 'COW MILK', NULL, NULL),\n"
                    + "  (1107, 'None', 'None', NULL),\n"
                    + "  (\n"
                    + "    1220,\n"
                    + "    'WHO STAGE 1 PEDS',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (5555, 'Married', 'Married', NULL),\n"
                    + "  (\n"
                    + "    1060,\n"
                    + "    'Living with partner ',\n"
                    + "    'Co-habiting',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (5615, 'Not married', 'Single', NULL),\n"
                    + "  (1107, 'None', 'None', NULL),\n"
                    + "  (\n"
                    + "    1185,\n"
                    + "    'TREATMENT',\n"
                    + "    'Treatment',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1391,\n"
                    + "    'PHYSICAL EXAM',\n"
                    + "    'peadditional',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    161011,\n"
                    + "    'Free text comment',\n"
                    + "    'pedadditional',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    142412,\n"
                    + "    'Diarrhea',\n"
                    + "    'Diarrhea',\n"
                    + "    'dur_diarh'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    832,\n"
                    + "    'Weight loss',\n"
                    + "    'Recent Weight Loss',\n"
                    + "    'dur_weigthl'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    159298,\n"
                    + "    'visual impairment',\n"
                    + "    'New Visual Imparity',\n"
                    + "    'dur_visimp'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    864,\n"
                    + "    'GENITAL SORES',\n"
                    + "    'Genital Discharge',\n"
                    + "    'dur_gensore'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165326,\n"
                    + "    'Cardiovascular',\n"
                    + "    'pecardiovascular',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165331,\n"
                    + "    'Glands',\n"
                    + "    'pedpeglands',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165327,\n"
                    + "    'Head/Eye/ENT',\n"
                    + "    'peheadeye',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165333,\n"
                    + "    'Genitalia',\n"
                    + "    'pegenitalia',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165316,\n"
                    + "    'Respiratory',\n"
                    + "    'gerespiratory',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165325,\n"
                    + "    'Neurological',\n"
                    + "    'geneurological',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165339,\n"
                    + "    'Mental status',\n"
                    + "    'gementalstatus',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165318, 'Skin', 'peskin', NULL),\n"
                    + "  (\n"
                    + "    165313,\n"
                    + "    'General appearance',\n"
                    + "    'pegenappearance',\n"
                    + "    NULL\n"
                    + "  ) ;\n"
                    + "", Statement.RETURN_GENERATED_KEYS);
            icconcept.executeUpdate();
            DatabaseHandler.getInstance().getApinConnection().commit();
        } catch (SQLException ex) {
            Logger.getLogger(FXMLDocumentController.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void createPharmacyConcept() {
        try {
            DatabaseHandler.getInstance().getApinConnection().setAutoCommit(false);

            dropTable = DatabaseHandler.getInstance().getApinConnection().prepareStatement(
                    String.format("DROP TABLE IF EXISTS %s", "parmacy_concepts"));
            dropTable.execute();

            String sql_stmt = "CREATE TABLE `parmacy_concepts` (\n"
                    + "  `concept_id` double DEFAULT NULL,\n"
                    + "  `concept` varchar(255) DEFAULT NULL,\n"
                    + "  `cisproconcepts` varchar(255) DEFAULT NULL,\n"
                    + "  `conceptvalue` varchar(255) DEFAULT NULL\n"
                    + ") ENGINE=InnoDB DEFAULT CHARSET=utf8;";

            statement = DatabaseHandler.getInstance().getApinConnection().createStatement();
            statement.executeUpdate(sql_stmt);

            icconcept = DatabaseHandler.getInstance().getApinConnection().prepareStatement(
                    "INSERT INTO `parmacy_concepts` (\n"
                    + "  `concept_id`,\n"
                    + "  `concept`,\n"
                    + "  `cisproconcepts`,\n"
                    + "  `conceptvalue`\n"
                    + ") \n"
                    + "VALUES\n"
                    + "  (\n"
                    + "    164181,\n"
                    + "    'Visit type',\n"
                    + "    'visittype',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165050,\n"
                    + "    'Prenancy/Breastfeeding Status',\n"
                    + "    'pregyn',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165774,\n"
                    + "    'Pick Up Reason',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165836,\n"
                    + "    'Number of missed doses per month',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165832,\n"
                    + "    'Adherence counseling offering',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165720,\n"
                    + "    'Treatment age group',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165708,\n"
                    + "    'Current Regimen Line',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164507,\n"
                    + "    'Child 1st line ARV regimen',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162240,\n"
                    + "    'Human immunodeficiency virus treatment regimen',\n"
                    + "    'Human_immunodeficiency_virus_treatment',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    159368,\n"
                    + "    'Medication duration',\n"
                    + "    'regduration1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165725,\n"
                    + "    'ARV Drug Strength',\n"
                    + "    'drugdose1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165723,\n"
                    + "    'Drug Frequency',\n"
                    + "    'frequency',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    160856,\n"
                    + "    'Quantity of medication prescribed per dose',\n"
                    + "    'drugdose1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1443,\n"
                    + "    'Medication dispensed',\n"
                    + "    'drugno1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165724,\n"
                    + "    'ARV Medication',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165726,\n"
                    + "    'Drugs for OI Prophylaxis',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165725,\n"
                    + "    'ARV Drug Strength',\n"
                    + "    'drugdose1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    159368,\n"
                    + "    'Medication duration',\n"
                    + "    'regduration1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1443,\n"
                    + "    'Medication dispensed',\n"
                    + "    'drugno1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165723,\n"
                    + "    'Drug Frequency',\n"
                    + "    'frequency',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    160856,\n"
                    + "    'Quantity of medication prescribed per dose',\n"
                    + "    'drugdose1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165727, 'OI drugs', 'oidrug', NULL),\n"
                    + "  (\n"
                    + "    165726,\n"
                    + "    'Drugs for OI Prophylaxis',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1443,\n"
                    + "    'Medication dispensed',\n"
                    + "    'drugno1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165723,\n"
                    + "    'Drug Frequency',\n"
                    + "    'frequency',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165727, 'OI drugs', 'oidrug', NULL),\n"
                    + "  (\n"
                    + "    159368,\n"
                    + "    'Medication duration',\n"
                    + "    'regduration1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165725,\n"
                    + "    'ARV Drug Strength',\n"
                    + "    'drugdose1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    160856,\n"
                    + "    'Quantity of medication prescribed per dose',\n"
                    + "    'drugdose1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165728,\n"
                    + "    'Drug Prescription for Anti-TB drugs',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165723,\n"
                    + "    'Drug Frequency',\n"
                    + "    'frequency',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165304,\n"
                    + "    'Anti-TB Drugs',\n"
                    + "    'tbdrug',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1443,\n"
                    + "    'Medication dispensed',\n"
                    + "    'drugno1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    159368,\n"
                    + "    'Medication duration',\n"
                    + "    'regduration1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    160856,\n"
                    + "    'Quantity of medication prescribed per dose',\n"
                    + "    'drugdose1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165725,\n"
                    + "    'ARV Drug Strength',\n"
                    + "    'drugdose1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165728,\n"
                    + "    'Drug Prescription for Anti-TB drugs',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165725,\n"
                    + "    'ARV Drug Strength',\n"
                    + "    'drugdose1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165304,\n"
                    + "    'Anti-TB Drugs',\n"
                    + "    'tbdrug',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165723,\n"
                    + "    'Drug Frequency',\n"
                    + "    'frequency',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    160856,\n"
                    + "    'Quantity of medication prescribed per dose',\n"
                    + "    'drugdose1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    159368,\n"
                    + "    'Medication duration',\n"
                    + "    'regduration1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1443,\n"
                    + "    'Medication dispensed',\n"
                    + "    'drugno1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164989,\n"
                    + "    'Orered date',\n"
                    + "    'visitdate',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164989,\n"
                    + "    'Orered date',\n"
                    + "    'visitdate',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165257,\n"
                    + "    'CTX prophylaxis',\n"
                    + "    'CTX',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    160862,\n"
                    + "    'OD (once daily)',\n"
                    + "    'OD',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165633,\n"
                    + "    '30/60/50mg',\n"
                    + "    '300/300/600',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165633,\n"
                    + "    '30/60/50mg',\n"
                    + "    '300/300/600mg',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165620,\n"
                    + "    '150/300/200mg',\n"
                    + "    '60/30mg/50mg/5ml',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164505,\n"
                    + "    'Lamivudine / Efavirenz / Tenofovir',\n"
                    + "    'TDF/3TC/EFV',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    161364,\n"
                    + "    'lamivudine / tenofovir',\n"
                    + "    '3TC/AZT/NVP',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    NULL,\n"
                    + "    'LAMIVUDINE / ZIDOVUDINE',\n"
                    + "    'TDF/3TC',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    630,\n"
                    + "    'ABACAVIR / LAMIVUDINE',\n"
                    + "    '3TC/AZT',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    103166,\n"
                    + "    'EFAVIRENZ',\n"
                    + "    'EFV',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    75523,\n"
                    + "    'ZIDOVUDINE',\n"
                    + "    'AZT',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    159809,\n"
                    + "    'ATAZANAVIR AND RITONAVIR',\n"
                    + "    'ATV/r',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    794,\n"
                    + "    'LOPINAVIR / RITONAVIR',\n"
                    + "    'LPV/r',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    74258,\n"
                    + "    'DARUNAVIR',\n"
                    + "    'DRV',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    83412,\n"
                    + "    'RITONAVIR',\n"
                    + "    'RTV',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162796,\n"
                    + "    'Darunavir / Ritonavir',\n"
                    + "    'DRV/r',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    80586,\n"
                    + "    'NEVIRAPINE',\n"
                    + "    'NVP',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    70056,\n"
                    + "    'ABACAVIR',\n"
                    + "    'ABC',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    154378,\n"
                    + "    'Raltegravir',\n"
                    + "    'RTV',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165631,\n"
                    + "    'Dolutegravir',\n"
                    + "    'DTC',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164505,\n"
                    + "    'Lamivudine / Efavirenz / Tenofovir',\n"
                    + "    'FDC (3TC/AZT/NVP)',\n"
                    + "    '4.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    630,\n"
                    + "    'ABACAVIR / LAMIVUDINE',\n"
                    + "    'ABC/3TC',\n"
                    + "    '0.000000'\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1443,\n"
                    + "    'Medication dispensed',\n"
                    + "    'oiqty',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    159368,\n"
                    + "    'Medication duration',\n"
                    + "    'oiduration',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1443,\n"
                    + "    'Medication dispensed',\n"
                    + "    'tbqty',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165724,\n"
                    + "    'ARV Medication',\n"
                    + "    'drugname1',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165728,\n"
                    + "    'Drug Prescription FOR Anti-TB drugs',\n"
                    + "    'Drug_prescription_for_Anti-TB_drugs',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165726,\n"
                    + "    'Drugs FOR OI Prophylaxis',\n"
                    + "    'Drugs_FOR_OI_Prophylaxis',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (1065, 'Yes', 'Yes', NULL),\n"
                    + "  (1066, 'No', 'No', NULL),\n"
                    + "  (\n"
                    + "    159368,\n"
                    + "    'Medication duration',\n"
                    + "    'tbduration',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165774,\n"
                    + "    'Pick Up Reason',\n"
                    + "    'refillyn',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164989,\n"
                    + "    'Orered DATE',\n"
                    + "    'ordered_date',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (1675, 'RHZE/RH', 'INH', NULL),\n"
                    + "  (NULL, NULL, '', NULL),\n"
                    + "(164505, 'TDF-3TC-EFV ', NULL, NULL),\n"
                    + "  (104565, 'TDF-FTC-EFV ', NULL, NULL),\n"
                    + "  (\n"
                    + "    1652,\n"
                    + "    '3TC-AZT-NVP',\n"
                    + "    '3TC/AZT/NVP',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1652,\n"
                    + "    'AZT-3TC-NVP ',\n"
                    + "    '3TC/AZT/NVP/NVP',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    1652,\n"
                    + "    'AZT-3TC-NVP ',\n"
                    + "    'AZT/3TC/NVP',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (162199, 'ABC-3TC-NVP ', NULL, NULL),\n"
                    + "  (\n"
                    + "    165690,\n"
                    + "    'ABC-FTC-NVP ',\n"
                    + "    '3TC/AZT',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (160124, 'AZT-3TC-EFV ', NULL, NULL),\n"
                    + "  (165681, 'TDF-3TC-DTG ', NULL, NULL),\n"
                    + "  (165682, 'TDF-FTC-DTG ', NULL, NULL),\n"
                    + "  (162565, 'TDF-3TC-NVP ', NULL, NULL),\n"
                    + "  (\n"
                    + "    164854,\n"
                    + "    'TDF-FTC-NVP ',\n"
                    + "    'TDF/3TC/EFV/NVP',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165686,\n"
                    + "    'TDF-3TC-EFV400 ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165687,\n"
                    + "    'TDF-FTC-EFV400 ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165691,\n"
                    + "    'ABC-3TC-DTG ',\n"
                    + "    'ABC/3TC/ATV/r',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165692, 'ABC-FTC-DTG ', NULL, NULL),\n"
                    + "  (\n"
                    + "    165693,\n"
                    + "    'ABC-3TC-EFV400 ',\n"
                    + "    '3TC/AZT/NVP/3TC/AZT',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165694,\n"
                    + "    'ABC-FTC-EFV400 ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162200,\n"
                    + "    'ABC-3TC-LPV/r ',\n"
                    + "    'ABC/3TC/LPV/r',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162561,\n"
                    + "    'AZT-3TC-LPV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162563,\n"
                    + "    'ABC-3TC-EFV ',\n"
                    + "    'ABC/3TC/EFV',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165695, 'AZT-3TC-RAL ', NULL, NULL),\n"
                    + "  (\n"
                    + "    164512,\n"
                    + "    'TDF-3TC-ATV/r ',\n"
                    + "    'TDF/3TC/AZT/ATV/r',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164512,\n"
                    + "    'TDF-3TC-ATV/r ',\n"
                    + "    'TDF/3TC/ATV/r',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162561,\n"
                    + "    'AZT-3TC-LPV/r ',\n"
                    + "    '3TC/AZT/NVP/LPV/r',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162201,\n"
                    + "    'TDF-3TC-LPV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164511,\n"
                    + "    'AZT-3TC-ATV/r ',\n"
                    + "    'EFV/ATV/r',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162200,\n"
                    + "    'ABC-3TC-LPV/r ',\n"
                    + "    'EFV',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165695, 'AZT-3TC-RAL ', 'NVP', NULL),\n"
                    + "  (\n"
                    + "    165696,\n"
                    + "    'ABC-3TC-RAL ',\n"
                    + "    'TDF/3TC',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165523,\n"
                    + "    'TDF-FTC-LPV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162201,\n"
                    + "    'TDF-3TC-LPV/r ',\n"
                    + "    'TDF/3TC/LPV/r',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165524,\n"
                    + "    'TDF-FTC-ATV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162561,\n"
                    + "    'AZT-3TC-LPV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162200,\n"
                    + "    'ABC-3TC-LPV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162560,\n"
                    + "    'D4T-3TC-LPV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165525, 'DDI-3TC-NVP ', NULL, NULL),\n"
                    + "  (165526, 'ABC-3TC-DDI ', NULL, NULL),\n"
                    + "  (\n"
                    + "    165527,\n"
                    + "    'TDF-FTC-SQV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165528,\n"
                    + "    'TDF-3TC-SQV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165529,\n"
                    + "    'AZT-3TC-SQV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165530,\n"
                    + "    'AZT-TDF-3TC-LPV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165531,\n"
                    + "    'TDF-AZT-FTC-SQV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165532,\n"
                    + "    'TDF-AZT-3TC-SQV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165533,\n"
                    + "    'TDF-3TC-IDV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165534,\n"
                    + "    'AZT-3TC-IDV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165535,\n"
                    + "    'TDF-AZT-FTC-IDV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165536,\n"
                    + "    'TDF-AZT-3TC-IDV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165537,\n"
                    + "    'TDF-AZT-3TC-ATV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164512,\n"
                    + "    'TDF-3TC-ATV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165539,\n"
                    + "    'TDF-FTC-IDV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162564,\n"
                    + "    'ABC-AZT-LPV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165540,\n"
                    + "    'AZT-TDF-FTC-LPV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165541,\n"
                    + "    'ABC-DDI-SQV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    165542,\n"
                    + "    'TDF-DDI-IDV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162559,\n"
                    + "    'ABC-DDI-LPV/r ',\n"
                    + "    '3TC/ZDV/NVP',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (1652, 'AZT-3TC-NVP ', NULL, NULL),\n"
                    + "  (164854, 'TDF-FTC-NVP ', NULL, NULL),\n"
                    + "  (792, 'D4T-3TC-NVP ', NULL, NULL),\n"
                    + "  (162199, 'ABC-3TC-NVP ', NULL, NULL),\n"
                    + "  (\n"
                    + "    160124,\n"
                    + "    'AZT-3TC-EFV ',\n"
                    + "    '3TC/AZT/EFV',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    104565,\n"
                    + "    'TDF-FTC-EFV ',\n"
                    + "    'TDF/FTC/EFV',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (160104, 'D4T-3TC-EFV ', NULL, NULL),\n"
                    + "  (162563, 'ABC-3TC-EFV ', NULL, NULL),\n"
                    + "  (\n"
                    + "    817,\n"
                    + "    'ABC-3TC-AZT ',\n"
                    + "    'ABC/3TC/AZT',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (162565, 'TDF-3TC-NVP ', NULL, NULL),\n"
                    + "  (165522, 'TDF-3TC-AZT ', NULL, NULL),\n"
                    + "  (\n"
                    + "    164505,\n"
                    + "    'TDF-3TC-EFV ',\n"
                    + "    'TDF/3TC/EFV/ABC/3TC/LPV/r',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164505,\n"
                    + "    'TDF-3TC-EFV ',\n"
                    + "    'TDF/3TC/EFV/3TC/ZDV/NVP',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    164505,\n"
                    + "    'TDF-3TC-EFV ',\n"
                    + "    'TDF/3TC/EFV',\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165525, 'DDI-3TC-NVP ', NULL, NULL),\n"
                    + "  (\n"
                    + "    162200,\n"
                    + "    'ABC-3TC-LPV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (\n"
                    + "    162561,\n"
                    + "    'AZT-3TC-LPV/r ',\n"
                    + "    NULL,\n"
                    + "    NULL\n"
                    + "  ),\n"
                    + "  (165526, 'ABC-3TC-DDI ', NULL, NULL)");
            icconcept.executeUpdate();
            DatabaseHandler.getInstance().getApinConnection().commit();
        } catch (SQLException ex) {
            Logger.getLogger(FXMLDocumentController.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void createAdultICEConcept() {
        try {
            DatabaseHandler.getInstance().getApinConnection().setAutoCommit(false);

            dropTable = DatabaseHandler.getInstance().getApinConnection().prepareStatement(
                    String.format("DROP TABLE IF EXISTS %s", "concept_adultice"));
            dropTable.execute();

            String sql_stmt = "CREATE TABLE IF NOT EXISTS `concept_adultice` (\n"
                    + "  `concept_id` int(11) DEFAULT NULL,\n"
                    + "  `name` varchar(6885) DEFAULT NULL,\n"
                    + "  `cisproconcepts` varchar(2295) DEFAULT NULL\n"
                    + ") ENGINE=InnoDB DEFAULT CHARSET=latin1;";

            statement = DatabaseHandler.getInstance().getApinConnection().createStatement();
            statement.executeUpdate(sql_stmt);

            icconcept = DatabaseHandler.getInstance().getApinConnection().prepareStatement(
                    "INSERT INTO `concept_adultice` (`concept_id`, `name`, `cisproconcepts`) VALUES\n"
                    + "(512, 'Rash', 'Rash'),\n"
                    + "(832, 'Weight loss', 'Recent Weight Loss'),\n"
                    + "(864, 'GENITAL SORES', 'Genital Sores'),\n"
                    + "(1065, 'Yes', 'Yes'),\n"
                    + "(1066, 'No', 'No'),\n"
                    + "(1067, 'Unknown', 'Uncertain'),\n"
                    + "(1107, 'None', 'None*'),\n"
                    + "(1434, 'CURRENTLY PREGNANT', 'currentlypregnant'),\n"
                    + "(5632, 'CURRENTLY BREASTFEEDING CHILD', 'currentlybreastf'),\n"
                    + "(133027, 'Night sweats', 'Night Sweats'),\n"
                    + "(133473, 'Nausea and Vomiting', 'Nausea/Vomitting'),\n"
                    + "(139084, 'Headache', 'Headache'),\n"
                    + "(140238, 'Fever', 'Fever/Chills'),\n"
                    + "(142373, 'Difficulty breathing', 'Shortness of Breath'),\n"
                    + "(142412, 'Diarrhea', 'Chronic Diarrhea'),\n"
                    + "(143264, 'Cough', 'Cough'),\n"
                    + "(1438, 'gestational age wks', 'gestationalage'),\n"
                    + "(879, 'Itching', 'Itching'),\n"
                    + "(159298, 'visual impairment', 'New Visual Imparity'),\n"
                    + "(159423, 'HIV status disclosed to partner', 'Spouse'),\n"
                    + "(159424, 'HIV status disclosed to other family members', 'Family Member'),\n"
                    + "(159425, 'HIV status disclosed to friends or neighbors', 'Friend'),\n"
                    + "(512, 'Skin rash', 'Rash'),\n"
                    + "(1427, 'Last menstrual period', 'lastmenstrualperiod'),\n"
                    + "(5596, 'Expected date of delivery', 'edd'),\n"
                    + "(105281, 'CTX', 'CTX'),\n"
                    + "(5622, 'Other', 'otherspec'),\n"
                    + "(162724, 'Health facility name', 'prevfacilityname'),\n"
                    + "(163074, 'Numbness and tingling of skin', 'Numbness/Tingling'),\n"
                    + "(164800, 'Tuberculosis screening status', 'patacc_tb'),\n"
                    + "(165045, 'Additional Comments', 'addiotnalsymcmments'),\n"
                    + "(165240, 'PMTCT Only', 'Earlier ARV not transfer in'),\n"
                    + "(160221, 'Past medical history (text)', 'pastmedicalhist'),\n"
                    + "(165303, 'ART', 'ART'),\n"
                    + "(165304, 'Anti-TB Drugs', 'Anti-TB'),\n"
                    + "(165426, 'Relevant Family History', 'relfamilyhist'),\n"
                    + "(165586, 'Previous ARV exposure', 'prevarvexp'),\n"
                    + "(165601, 'Hospitalization', 'hospitalization'),\n"
                    + "(165675, 'Patient has any known drug allergies', 'knwnallergy'),\n"
                    + "(165676, 'Patient has disclosed HIV status to spiritual leader', 'Spiritual Leader'),\n"
                    + "(165677, 'Patient has not disclosed HIV status', 'No one'),\n"
                    + "(165679, 'HIV status can be discussed with', 'hivstatdiscussion'),\n"
                    + "(165680, 'Presenting Complaints', 'presentingcomplaint'),\n"
                    + "(165712, 'Earlier ARV but not a transfer in', 'Transfer in with records'),\n"
                    + "(165713, 'Has never received ARVs', 'Never recieved ARVs'),\n"
                    + "(165714, 'On Previous ARV exposure', 'prevarvtype'),\n"
                    + "(165829, 'Duration from', 'prevdurationofcarefromdate'),\n"
                    + "(165830, 'Duration to', 'prevdurationofcaretodate');");
            icconcept.executeUpdate();
            DatabaseHandler.getInstance().getApinConnection().commit();
        } catch (SQLException ex) {
            Logger.getLogger(FXMLDocumentController.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void createLabConcept() {
        try {
            DatabaseHandler.getInstance().getApinConnection().setAutoCommit(false);

            dropTable = DatabaseHandler.getInstance().getApinConnection().prepareStatement(
                    String.format("DROP TABLE IF EXISTS %s", "concept_lab"));
            dropTable.execute();

            String sql_stmt = "CREATE TABLE IF NOT EXISTS `concept_lab` (\n"
                    + "  `concept_id` double DEFAULT NULL,\n"
                    + "  `NAME` varchar(6885) DEFAULT NULL,\n"
                    + "  `cisproconcepts` varchar(6885) DEFAULT NULL,\n"
                    + "  `datatype` int(11) DEFAULT NULL\n"
                    + ") ENGINE=InnoDB DEFAULT CHARSET=latin1;";

            statement = DatabaseHandler.getInstance().getApinConnection().createStatement();
            statement.executeUpdate(sql_stmt);

            icconcept = DatabaseHandler.getInstance().getApinConnection().prepareStatement(
                    "INSERT INTO `concept_lab` (`concept_id`, `NAME`, `cisproconcepts`, `datatype`) VALUES\n"
                    + "(45, 'URINE PREGNANCY TEST', 'Pregnancy', NULL),\n"
                    + "(299, 'VDRL', 'VDRL', NULL),\n"
                    + "(302, 'URINALYSIS ORDER', 'Urinalysis', NULL),\n"
                    + "(653, 'SERUM GLUTAMIC-OXALOACETIC TRANSAMINASE', 'SGOT', NULL),\n"
                    + "(654, 'SERUM GLUTAMIC-PYRUVIC TRANSAMINASE', 'ALT/SGPT', NULL),\n"
                    + "(655, 'TOTAL BILIRUBIN', 'Total Bilirubin', NULL),\n"
                    + "(678, 'WHITE BLOOD CELLS', 'WBC', NULL),\n"
                    + "(678, 'WBC', 'WBC', NULL),\n"
                    + "(729, 'Platelets', 'Platelets', NULL),\n"
                    + "(730, 'CD4 PERCENT', 'CD4%', NULL),\n"
                    + "(785, 'ALKALINE PHOSPHATASE', 'Alk. Phosphatase', NULL),\n"
                    + "(856, 'HIV VIRAL LOAD', 'Viral Load', NULL),\n"
                    + "(856, 'VIRAL LOAD', 'Viral Load', NULL),\n"
                    + "(887, 'GLUCOSE', 'GLUCOSE', NULL),\n"
                    + "(1006, 'TOTAL CHOLESTEROL', 'Total Cholesterol', NULL),\n"
                    + "(1007, 'HDL', 'HDL', NULL),\n"
                    + "(1007, 'HDL', 'HDL', NULL),\n"
                    + "(1008, 'LOW-DENSITY LIPOPROTEIN CHOLESTEROL', 'LDL', NULL),\n"
                    + "(1008, 'LDL', 'LDL', NULL),\n"
                    + "(1008, 'LDL', 'LDL', NULL),\n"
                    + "(1009, 'TRIGLYCERIDES', 'Triglyceride', NULL),\n"
                    + "(1009, 'TG', 'Triglyceride', NULL),\n"
                    + "(1009, 'TG', 'Triglyceride', NULL),\n"
                    + "(1009, 'TRIG', 'Triglyceride', NULL),\n"
                    + "(1015, 'PCV', 'PCV/Hb', NULL),\n"
                    + "(1021, 'LYMPHOCYTES', NULL, NULL),\n"
                    + "(1022, 'POLYMORPHONUCLEAR CELLS', 'Polymorph', NULL),\n"
                    + "(1023, 'MONOCYTES', 'Monocytes', NULL),\n"
                    + "(1024, 'EOSINOPHILS', 'Eosinophils', NULL),\n"
                    + "(1025, 'BASOPHILS', 'Basophils', NULL),\n"
                    + "(1132, 'NA', 'Na+', NULL),\n"
                    + "(1132, 'NA', 'Na+', NULL),\n"
                    + "(1133, 'K', 'K+', NULL),\n"
                    + "(1875, 'URINE PROTEIN (DIP STICK)', 'Urinalysis: PROTEIN', NULL),\n"
                    + "(5497, 'CD4 COUNT', 'CD4', NULL),\n"
                    + "(5497, 'CD4', 'CD4', NULL),\n"
                    + "(5497, 'CD4', 'CD4', NULL),\n"
                    + "(159430, 'HBsAg', 'HBsAG (*At Baseline)', NULL),\n"
                    + "(159661, 'creatinine measurement, urine, 24 hour', NULL, NULL),\n"
                    + "(160053, 'Fasting Glucose', 'Fasting Glucose', NULL),\n"
                    + "(164982, 'Reported by', 'reportedby', NULL),\n"
                    + "(164983, 'Checked by', 'checkedby', NULL),\n"
                    + "(1542, 'Occupation', 'jobstatus', NULL),\n"
                    + "(164984, 'Date Checked', 'checkdate', NULL),\n"
                    + "(164989, 'Orered date', 'cliniciandate', NULL),\n"
                    + "(164989, 'Ordered date', 'cliniciandate', NULL),\n"
                    + "(165414, 'Date Reported', 'reportdate', NULL),\n"
                    + "(165562, 'HCV status', 'HCV Antibody', NULL),\n"
                    + "(1054, 'Civil status', 'maritalstatus', NULL),\n"
                    + "(1712, 'HIGHEST EDUCATION LEVEL', 'educationallevel', NULL),\n"
                    + "(1712, 'Education Level', 'educationallevel', NULL),\n"
                    + "(1712, 'Current education level', 'educationallevel', NULL),\n"
                    + "(1712, 'Highest Educational Level', 'educationallevel', NULL),\n"
                    + "(163260, 'Date first seen by healthcare provider', 'enroldate', NULL),\n"
                    + "(163260, 'Date of first visit', 'enroldate', NULL),\n"
                    + "(164981, 'Name of Clinician', 'Clinicianname', NULL),\n"
                    + "(161199, 'Cytology', 'Cytology: VIA/Pap Smear', NULL),\n"
                    + "(162476, 'Specimen sources', 'pcrsampletype', NULL),\n"
                    + "(159951, 'specimen date', 'pcrsamplecolldate', NULL),\n"
                    + "(1366, 'MALARIA SMEAR, QUALITATIVE', 'Malaria smear', NULL),\n"
                    + "(1319, 'LYMPHOCYTE COUNT', 'Lymphocytes', NULL),\n"
                    + "(164364, 'Serum creatinine (mg/dL)', 'Creatinine', NULL);");
            icconcept.executeUpdate();
            DatabaseHandler.getInstance().getApinConnection().commit();
        } catch (SQLException ex) {
            Logger.getLogger(FXMLDocumentController.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void createLabCheckBoxesConcept() {
        try {
            DatabaseHandler.getInstance().getApinConnection().setAutoCommit(false);

            dropTable = DatabaseHandler.getInstance().getApinConnection().prepareStatement(
                    String.format("DROP TABLE IF EXISTS %s", "concept_lab_checkboxes"));
            dropTable.execute();

            String sql_stmt = "CREATE TABLE IF NOT EXISTS `concept_lab_checkboxes` (\n"
                    + "  `concept_id` int(11) DEFAULT NULL,\n"
                    + "  `name` varchar(20655) DEFAULT NULL,\n"
                    + "  `cisproconcepts` varchar(6885) DEFAULT NULL\n"
                    + ") ENGINE=InnoDB DEFAULT CHARSET=latin1;";

            statement = DatabaseHandler.getInstance().getApinConnection().createStatement();
            statement.executeUpdate(sql_stmt);

            icconcept = DatabaseHandler.getInstance().getApinConnection().prepareStatement(
                    "INSERT INTO `concept_lab_checkboxes` (`concept_id`, `name`, `cisproconcepts`) VALUES\n"
                    + "(1542, 'Occupation', 'jobstatus'),\n"
                    + "(164981, 'Name of Clinician', 'Clinicianname'),\n"
                    + "(164982, 'Reported by', 'reportedby'),\n"
                    + "(164983, 'Checked by', 'checkedby'),\n"
                    + "(164984, 'Date Checked', 'checkdate'),\n"
                    + "(164989, 'Orered date', 'cliniciandate'),\n"
                    + "(165414, 'Date Reported', 'reportdate'),\n"
                    + "(165731, 'CD4+ cell count Order', 'CD4'),\n"
                    + "(165732, 'WBC Order', 'WBC'),\n"
                    + "(165733, 'Lymphocytes order', 'Lymphocytes'),\n"
                    + "(165734, 'Monocytes Order', 'Monocytes'),\n"
                    + "(165735, 'Eosinophils Order', 'Eosinophils'),\n"
                    + "(165736, 'Basophils Order', 'Basophils'),\n"
                    + "(165737, 'PCV/Hb Order', 'PCV/Hb'),\n"
                    + "(165738, 'HCV antibody Order', 'HCV Antibody'),\n"
                    + "(165739, 'VDRL Order', 'VDRL'),\n"
                    + "(165740, 'ALT/SGPT Order', 'ALT/SGPT'),\n"
                    + "(165741, 'Alk. Phosphatase Order', 'Alk. Phosphatase'),\n"
                    + "(165742, 'Na+ Order', 'Na+'),\n"
                    + "(165743, 'Fasting Glucose Order', 'Fasting Glucose'),\n"
                    + "(165744, 'LDL Order', 'LDL'),\n"
                    + "(165745, 'Glucose Order', 'GLUCOSE'),\n"
                    + "(165746, 'Cytology/Pap Smear Order', 'Cytology: VIA/Pap Smear'),\n"
                    + "(165747, 'Pregnancy Order', 'Pregnancy'),\n"
                    + "(165748, 'CD4% Order', 'CD4%'),\n"
                    + "(165749, 'Polymorphs Order', 'Polymorph'),\n"
                    + "(165754, 'Platelets Order', 'Platelets'),\n"
                    + "(165755, 'HBsAG Order', 'HBsAG (*At Baseline)'),\n"
                    + "(165756, 'Creatinine Order', 'Creatinine'),\n"
                    + "(165757, 'AST/SGOT Order', 'AST/SGOT'),\n"
                    + "(165758, 'Total Bilirubin Order', 'Total Bilirubin'),\n"
                    + "(165759, 'K+ Order', 'K+'),\n"
                    + "(165760, 'Total Cholesterol Order', 'Total Cholesterol'),\n"
                    + "(165761, 'HDL Order', 'HDL'),\n"
                    + "(165762, 'Protein Order', 'Urinalysis: PROTEIN'),\n"
                    + "(165763, 'Triglyceride Order', 'Triglyceride'),\n"
                    + "(165764, 'Malaria smear Order', 'Malaria smear'),\n"
                    + "(165765, 'Viral Load Order', 'Viral Load');");
            icconcept.executeUpdate();
            DatabaseHandler.getInstance().getApinConnection().commit();
        } catch (SQLException ex) {
            Logger.getLogger(FXMLDocumentController.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void setMigrationField() {
        try {

            String sql_stmt = "CALL migrated()";

            statementalter = DatabaseHandler.getInstance().getApinConnection().createStatement();
            statementalter.executeUpdate(sql_stmt);
        } catch (SQLException ex) {
            Logger.getLogger(FXMLDocumentController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void updateMigrationField(String Table, String column, String columnToSet, String rowid) {
        if (!StringUtils.isNullOrEmpty(rowid)) {
            try {
                DatabaseHandler.getInstance().getApinConnection().setAutoCommit(false);
                String sql_stmt = "Update " + Table + " set " + column + " = 1 where " + columnToSet + " = " + rowid;
                statementUpdatenowa = DatabaseHandler.getInstance().getApinConnection().prepareStatement(sql_stmt);
                statementUpdatenowa.executeUpdate(sql_stmt);
                DatabaseHandler.getInstance().getApinConnection().commit();
            } catch (SQLException ex) {
                Logger.getLogger(FXMLDocumentController.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void resetMigrationField(String Table, String column) {
        if (!StringUtils.isNullOrEmpty(column)) {
            try {
                DatabaseHandler.getInstance().getApinConnection().setAutoCommit(false);
                String sql_stmt = "Update " + Table + " set " + column + " = 0";
                statementUpdatenow = DatabaseHandler.getInstance().getApinConnection().prepareStatement(sql_stmt);
                statementUpdatenow.executeUpdate(sql_stmt);
                DatabaseHandler.getInstance().getApinConnection().commit();
            } catch (SQLException ex) {
                Logger.getLogger(FXMLDocumentController.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void altResetMigrationField(String Table, String column, String columnToSet, String length) {
        if (!StringUtils.isNullOrEmpty(columnToSet)) {
            try {
                DatabaseHandler.getInstance().getApinConnection().setAutoCommit(false);
                String sql_stmt = "Update " + Table + " set " + column + " = 0 where length(" + columnToSet + ") = " + length;
                statementUpdatenowp = DatabaseHandler.getInstance().getApinConnection().prepareStatement(sql_stmt);
                statementUpdatenowp.executeUpdate(sql_stmt);
                DatabaseHandler.getInstance().getApinConnection().commit();
            } catch (SQLException ex) {
                Logger.getLogger(FXMLDocumentController.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private static class con {

        public con() {
        }
    }
}
